DESCRIPTION = "Minimal initramfs/initrd image"
LICENSE = "MIT"

AMD_INSTALL ??= ""

PACKAGE_INSTALL = "\
    ${VIRTUAL-RUNTIME_base-utils} \
    ${VIRTUAL-RUNTIME_dev_manager} \
    ${ROOTFS_BOOTSTRAP_INSTALL} \
    ${AMD_INSTALL} \
    "

IMAGE_FEATURES = ""
IMAGE_LINGUAS = ""

COPY_LIC_MANIFEST = "0"
COPY_LIC_DIRS = "0"

KERNELDEPMODDEPEND = ""

# initrd/initramfs size in kilobytes
# max 300000KB -> 300MB
INITRAMFS_MAXSIZE ?= "300000"

IMAGE_NAME_SUFFIX = ""
IMAGE_ROOTFS_SIZE = "0"
IMAGE_ROOTFS_EXTRA_SPACE = "0"

FORCE_RO_REMOVE ?= "1"

inherit core-image

IMAGE_FSTYPES = "${INITRAMFS_FSTYPE}"

IMAGE_POSTPROCESS_COMMAND = ""
